"use client";

// app/blog/[slug]/page.tsx
// =============================================================================
// AI Marketing Labs — Public Blog Post Page
// Full article render · SEO meta · Author bio · Related posts · ToC
// =============================================================================

import { useState, useEffect, useRef, useMemo } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { motion } from "framer-motion";
import {
  ArrowLeft, Clock, Calendar, Tag, Share2, Link2,
  CheckCircle2, ChevronRight,
  TrendingUp, Eye, Zap, Rss,
} from "lucide-react";

// ─────────────────────────────────────────────────────────────────────────────
// Re-use mock data (in production, fetch from Supabase by slug)
// ─────────────────────────────────────────────────────────────────────────────
const MOCK_POST = {
  slug:            "generative-engine-optimisation-enterprise-guide",
  title:           "Generative Engine Optimisation: The Definitive Enterprise Guide for 2026",
  excerpt:         "As AI-powered search engines displace traditional SERP rankings, enterprise organisations must adapt their content architecture to achieve citation within large language model outputs.",
  category:        "geo_optimisation",
  tags:            ["GEO", "AI Search", "Content Strategy", "Technical SEO"],
  read_time:       14,
  published_at:    "2026-04-10",
  updated_at:      "2026-04-12",
  author_name:     "AI Marketing Labs Editorial",
  author_bio:      "The AI Marketing Labs Editorial team comprises enterprise SEO practitioners, GEO researchers, and technical content strategists operating from Hatfield, UK. We use the AI Marketing Labs platform to test every strategy we publish.",
  author_avatar:   "RE",
  view_count:      2841,
  meta_title:      "Generative Engine Optimisation (GEO): Enterprise Guide 2026 | AI Marketing Labs",
  meta_description:"The definitive enterprise guide to GEO — how to optimise content for AI-powered search engines including ChatGPT, Perplexity, and Google AI Overviews.",
  focus_keyword:   "generative engine optimisation",
  content: `
## What Is Generative Engine Optimisation?

Generative Engine Optimisation (GEO) is the practice of structuring, formatting, and distributing content in ways that increase the probability of citation by large language model-powered search engines — including Google AI Overviews, Perplexity, ChatGPT Browse, and Microsoft Copilot.

Unlike traditional SEO, which optimises for a ten-blue-links result page, GEO targets the answer layer — the synthesised response generated by the AI before a user ever clicks a link. For enterprise organisations, achieving citation in this layer is increasingly critical as click-through rates from traditional organic results decline.

## Why GEO Matters More Than Traditional SEO in 2026

According to our internal analysis of 2,400 AI Overview responses across competitive B2B keywords, pages that appear in AI-generated answers receive 34% higher brand recall and 22% higher direct navigation rates than those that rank in positions 1–3 in the traditional SERP but are not cited by AI.

The implication is significant: **ranking first is no longer sufficient**. A page at position four that is consistently cited by Perplexity and ChatGPT will outperform a position-one result that the AI never references.

## The Three Pillars of Enterprise GEO

### 1. Structured Authority Signals

AI engines draw heavily on content that demonstrates clear expertise, authoritativeness, and trustworthiness — but they operationalise these signals differently than Google's ranking algorithms.

The most reliable structural signals for AI citation include:

- **Named authorship** with verifiable credentials and linked author profiles
- **Explicit methodology disclosure** — AI engines favour content that describes how conclusions were reached
- **Primary data and original research** — cited more frequently than aggregated third-party summaries
- **Date-stamped recency signals** — both in metadata and within the prose itself

### 2. Content Formatting for Machine Comprehension

LLMs parse content differently to human readers. The following formatting patterns correlate with higher citation probability based on our GEO Citation Score analysis:

- **Definitions at scale** — lead paragraphs that clearly define the primary topic before expanding
- **Numbered and bulleted structure** — AI models extract and re-compose lists efficiently
- **FAQ schema and structured Q&A** — directly maps to the question-answer format AI engines generate
- **Statistical claims with source attribution** — cited because they provide verifiable specificity

### 3. Semantic Distribution Strategy

A single well-optimised page is insufficient for sustained GEO performance. Enterprise organisations need a semantic distribution strategy that achieves coverage across the full topic graph of their primary subject area.

This requires:

1. **Hub-and-spoke architecture** — a definitive pillar page supported by subordinate cluster content
2. **Cross-platform syndication** — publishing content in formats consumable by AI training pipelines (RSS, structured HTML, schema-rich pages)
3. **Citation amplification** — earning references from established domains that AI engines trust as primary sources

## Technical Implementation Checklist

The following schema types have the highest impact on AI Overview and LLM citation probability:

- ✓ FAQ schema (FAQPage) on all informational content
- ✓ HowTo schema on process-oriented articles  
- ✓ Article schema with author, datePublished, dateModified
- ✓ BreadcrumbList for hierarchical content
- ✓ SpeakableSpecification for AI voice responses
- ✓ Dataset schema for original research and statistics

## Measuring GEO Performance

Traditional SEO metrics — rankings, impressions, clicks — do not capture GEO performance. We recommend tracking the following:

**AI Citation Score** — the percentage of target queries for which your domain appears in AI-generated responses. AI Marketing Labs tracks this across Google AI Overviews, Perplexity, and ChatGPT Browse.

**Share of AI Answer Voice** — within responses where your brand appears, what percentage of the synthesised content references your content directly?

**Citation-to-Click Attribution** — direct navigation events attributable to AI response exposure rather than traditional SERP click.

## Conclusion

GEO is not a replacement for SEO — it is an extension of it. Organisations that build strong topical authority, implement structured data rigorously, and produce original research will succeed in both channels. The key difference is intentionality: GEO requires explicitly designing content to be machine-readable and citation-worthy, not merely search-engine-visible.

The AI Marketing Labs platform tracks your AI Citation Score in real time across all major AI engines. If you have not yet connected your domain, the Getting Started guide in the dashboard walks through the integration in under 10 minutes.
  `,
};

const RELATED_POSTS = [
  { slug: "ai-overview-optimisation-schema-markup", title: "AI Overview Optimisation: How Schema Markup Increases Citation Probability by 34%", read_time: 10, category: "geo_optimisation" },
  { slug: "topical-authority-content-clusters-guide", title: "Building Topical Authority: The Hub-and-Spoke Content Cluster Framework", read_time: 12, category: "content_marketing" },
  { slug: "technical-seo-core-web-vitals-2026", title: "Core Web Vitals in 2026: What Has Changed and What Your Site Must Do Now", read_time: 9, category: "technical_seo" },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
const SP = { type: "spring", stiffness: 260, damping: 30, mass: 0.9 } as const;
function pv(delay = 0) {
  return { hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0, transition: { ...SP, delay } } };
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
}

function parseSections(content: string): { id: string; title: string; level: number }[] {
  const lines   = content.split("\n");
  const headings: { id: string; title: string; level: number }[] = [];
  for (const line of lines) {
    const m = line.match(/^(#{2,3})\s+(.+)/);
    if (m) {
      headings.push({
        level: m[1].length,
        title: m[2],
        id:    m[2].toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      });
    }
  }
  return headings;
}

function renderContent(content: string, brandColor: string): React.ReactNode[] {
  const blocks = content.trim().split(/\n\n+/);
  return blocks.map((block, i) => {
    // H2
    if (block.startsWith("## ")) {
      const text = block.slice(3);
      const id   = text.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      return (
        <h2 key={i} id={id} style={{ fontFamily: "var(--font-syne), sans-serif", fontSize: "clamp(1.3rem, 2.5vw, 1.6rem)", fontWeight: 800, color: "var(--text-primary)", letterSpacing: "-0.025em", lineHeight: 1.25, margin: "40px 0 16px", scrollMarginTop: "80px" }}>
          {text}
        </h2>
      );
    }
    // H3
    if (block.startsWith("### ")) {
      const text = block.slice(4);
      return (
        <h3 key={i} style={{ fontFamily: "var(--font-syne), sans-serif", fontSize: "1.15rem", fontWeight: 700, color: "var(--text-primary)", letterSpacing: "-0.015em", lineHeight: 1.3, margin: "28px 0 10px" }}>
          {text}
        </h3>
      );
    }
    // Bullet list
    if (block.split("\n").every(l => l.startsWith("- "))) {
      const items = block.split("\n").map(l => l.slice(2));
      return (
        <ul key={i} style={{ paddingLeft: "0", listStyle: "none", margin: "16px 0", display: "flex", flexDirection: "column", gap: "8px" }}>
          {items.map((item, j) => {
            const parts = item.split(/\*\*(.+?)\*\*/g);
            return (
              <li key={j} style={{ display: "flex", alignItems: "flex-start", gap: "10px", fontFamily: "var(--font-inter), sans-serif", fontSize: "15px", color: "var(--text-secondary)", lineHeight: 1.75 }}>
                <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: brandColor, marginTop: "9px", flexShrink: 0 }} />
                <span>
                  {parts.map((p, k) => k % 2 === 1
                    ? <strong key={k} style={{ color: "var(--text-primary)", fontWeight: 600 }}>{p}</strong>
                    : <span key={k}>{p}</span>
                  )}
                </span>
              </li>
            );
          })}
        </ul>
      );
    }
    // Numbered list
    if (block.split("\n").every(l => /^\d+\. /.test(l))) {
      const items = block.split("\n").map(l => l.replace(/^\d+\. /, ""));
      return (
        <ol key={i} style={{ paddingLeft: "0", listStyle: "none", margin: "16px 0", display: "flex", flexDirection: "column", gap: "8px", counterReset: "item" }}>
          {items.map((item, j) => (
            <li key={j} style={{ display: "flex", alignItems: "flex-start", gap: "12px", fontFamily: "var(--font-inter), sans-serif", fontSize: "15px", color: "var(--text-secondary)", lineHeight: 1.75 }}>
              <span style={{ width: "22px", height: "22px", borderRadius: "50%", background: `rgba(var(--brand-rgb),0.12)`, border: `1px solid rgba(var(--brand-rgb),0.25)`, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-dm-mono), monospace", fontSize: "10px", color: brandColor, fontWeight: 500, flexShrink: 0, marginTop: "2px" }}>
                {j + 1}
              </span>
              {item}
            </li>
          ))}
        </ol>
      );
    }
    // Checkmarks
    if (block.split("\n").every(l => l.startsWith("- ✓"))) {
      const items = block.split("\n").map(l => l.slice(4));
      return (
        <ul key={i} style={{ paddingLeft: "0", listStyle: "none", margin: "16px 0", display: "flex", flexDirection: "column", gap: "6px" }}>
          {items.map((item, j) => (
            <li key={j} style={{ display: "flex", alignItems: "flex-start", gap: "8px", fontFamily: "var(--font-dm-mono), monospace", fontSize: "13px", color: "var(--text-secondary)", lineHeight: 1.65 }}>
              <CheckCircle2 size={13} color="var(--signal-green)" style={{ marginTop: "2px", flexShrink: 0 }} />
              {item}
            </li>
          ))}
        </ul>
      );
    }
    // Bold inline
    const parts = block.split(/\*\*(.+?)\*\*/g);
    const rendered = parts.map((p, j) => j % 2 === 1
      ? <strong key={j} style={{ color: "var(--text-primary)", fontWeight: 600 }}>{p}</strong>
      : <span key={j}>{p}</span>
    );
    return (
      <p key={i} style={{ fontFamily: "var(--font-inter), sans-serif", fontSize: "16px", color: "var(--text-secondary)", lineHeight: 1.85, margin: "0 0 18px" }}>
        {rendered}
      </p>
    );
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Table of contents
// ─────────────────────────────────────────────────────────────────────────────
function TableOfContents({ sections, brandColor }: { sections: { id: string; title: string; level: number }[]; brandColor: string }) {
  const [active, setActive] = useState("");

  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => { entries.forEach(e => { if (e.isIntersecting) setActive(e.target.id); }); },
      { rootMargin: "-20% 0% -70% 0%", threshold: 0 }
    );
    sections.forEach(s => {
      const el = document.getElementById(s.id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, [sections]);

  return (
    <div style={{ position: "sticky", top: "80px" }} suppressHydrationWarning>
      <div style={{ fontFamily: "var(--font-syne), sans-serif", fontSize: "10px", fontWeight: 700, color: "var(--text-tertiary)", letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: "12px" }}>
        Contents
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
        {sections.map(s => (
          <button
            key={s.id}
            onClick={() => document.getElementById(s.id)?.scrollIntoView({ behavior: "smooth", block: "start" })}
            style={{
              fontFamily:   "var(--font-inter), sans-serif",
              fontSize:     "12px",
              color:        active === s.id ? brandColor : "var(--text-tertiary)",
              background:   "transparent",
              border:       "none",
              borderLeft:   `2px solid ${active === s.id ? brandColor : "var(--border)"}`,
              padding:      `5px ${s.level === 3 ? "18px" : "8px"}`,
              cursor:       "pointer",
              textAlign:    "left",
              lineHeight:   "1.4",
              transition:   "color 0.18s, border-color 0.18s",
              display:      "block",
              width:        "100%",
            }}
          >
            {s.title}
          </button>
        ))}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Page
// ─────────────────────────────────────────────────────────────────────────────
const ALL_POSTS = [
  MOCK_POST,
  { ...MOCK_POST, slug: "technical-seo-core-web-vitals-2026",          title: "Core Web Vitals in 2026: What Has Changed and What Your Site Must Do Now",                          focus_keyword: "core web vitals 2026",                    category: "technical_seo"      },
  { ...MOCK_POST, slug: "hatfield-uk-business-digital-strategy-2026",  title: "Hatfield UK Business District: A Digital Strategy Review for Q2 2026",                              focus_keyword: "Hatfield UK business digital strategy",   category: "business_insights"  },
  { ...MOCK_POST, slug: "dataforseo-api-integration-seo-platforms",    title: "How We Integrated DataForSEO to Power Real-Time Keyword Intelligence",                               focus_keyword: "DataForSEO API integration",               category: "platform_updates"   },
  { ...MOCK_POST, slug: "topical-authority-content-clusters-guide",    title: "Building Topical Authority: The Hub-and-Spoke Content Cluster Framework",                           focus_keyword: "topical authority content clusters",      category: "content_marketing"  },
  { ...MOCK_POST, slug: "competitor-backlink-gap-analysis-methodology",title: "Competitor Backlink Gap Analysis: A Systematic Methodology for Link Acquisition",                   focus_keyword: "competitor backlink gap analysis",        category: "seo_strategy"       },
  { ...MOCK_POST, slug: "ai-overview-optimisation-schema-markup",      title: "AI Overview Optimisation: How Schema Markup Increases Citation Probability by 34%",                 focus_keyword: "AI overview optimisation schema markup",  category: "geo_optimisation"   },
  { ...MOCK_POST, slug: "AI Marketing Labs-platform-case-study-organic-growth",   title: "Case Study: 85% Organic Traffic Growth in 6 Months Using AI Marketing Labs Intelligence",                     focus_keyword: "organic traffic growth case study",       category: "case_studies"       },
];
export default function BlogPostPage() {
  const params     = useParams();
  const brandColor = "#3b82f6";
  const slug       = typeof params.slug === "string" ? params.slug : Array.isArray(params.slug) ? params.slug[0] : "";
  const post       = ALL_POSTS.find(p => p.slug === slug) ?? MOCK_POST;
  const sections   = useMemo(() => parseSections(post.content), [post.content]);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem("AI Marketing Labs-brand");
    if (stored) document.documentElement.style.setProperty("--brand", stored);
  }, []);

  function copyLink() {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div style={{ background: "var(--bg)", minHeight: "100vh" }}>

      {/* Back nav */}
      <div style={{ borderBottom: "1px solid var(--border)", padding: "14px 24px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <Link
            href="/blog"
            style={{ display: "inline-flex", alignItems: "center", gap: "6px", fontFamily: "var(--font-inter), sans-serif", fontSize: "13px", fontWeight: 500, color: "var(--text-secondary)", textDecoration: "none", transition: "color 0.18s" }}
            onMouseEnter={e => (e.currentTarget as HTMLElement).style.color = "var(--text-primary)"}
            onMouseLeave={e => (e.currentTarget as HTMLElement).style.color = "var(--text-secondary)"}
          >
            <ArrowLeft size={13} />
            Back to Blog
          </Link>
        </div>
      </div>

      <div style={{ maxWidth: "1200px", margin: "0 auto", padding: "48px 24px 80px" }}>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 220px", gap: "60px", alignItems: "start" }}>

          {/* Main article */}
          <article>
            {/* Header */}
            <motion.div variants={pv(0)} initial="hidden" animate="visible">
              <div style={{ display: "flex", gap: "8px", marginBottom: "20px", flexWrap: "wrap" }}>
                <span style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "9px", color: brandColor, background: `rgba(var(--brand-rgb),0.10)`, border: `1px solid rgba(var(--brand-rgb),0.22)`, padding: "3px 10px", borderRadius: "100px", letterSpacing: "0.10em", textTransform: "uppercase" }}>
                  GEO Optimisation
                </span>
                {post.tags.slice(0, 3).map(tag => (
                  <span key={tag} style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "9px", color: "var(--text-tertiary)", background: "var(--card)", border: "1px solid var(--border)", padding: "3px 9px", borderRadius: "100px", letterSpacing: "0.06em" }}>
                    {tag}
                  </span>
                ))}
              </div>

              <h1 style={{ fontFamily: "var(--font-syne), sans-serif", fontSize: "clamp(1.7rem, 4vw, 2.6rem)", fontWeight: 800, color: "var(--text-primary)", letterSpacing: "-0.035em", lineHeight: 1.1, marginBottom: "20px" }}>
                {post.title}
              </h1>

              <p style={{ fontFamily: "var(--font-inter), sans-serif", fontSize: "17px", color: "var(--text-secondary)", lineHeight: 1.7, marginBottom: "24px", fontStyle: "italic" }}>
                {post.excerpt}
              </p>

              {/* Meta strip */}
              <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "16px 0", borderTop: "1px solid var(--border)", borderBottom: "1px solid var(--border)", marginBottom: "40px", flexWrap: "wrap", gap: "12px" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "16px", flexWrap: "wrap" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                    <div style={{ width: "32px", height: "32px", borderRadius: "50%", background: `linear-gradient(135deg, ${brandColor}, color-mix(in srgb, ${brandColor} 55%, #000))`, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-syne), sans-serif", fontSize: "10px", fontWeight: 700, color: "#fff" }}>
                      {post.author_avatar}
                    </div>
                    <div>
                      <div style={{ fontFamily: "var(--font-inter), sans-serif", fontSize: "13px", fontWeight: 600, color: "var(--text-primary)" }}>{post.author_name}</div>
                    </div>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: "5px" }}>
                    <Calendar size={11} color="var(--text-tertiary)" />
                    <span style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "11px", color: "var(--text-tertiary)" }}>{formatDate(post.published_at)}</span>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: "5px" }}>
                    <Clock size={11} color="var(--text-tertiary)" />
                    <span style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "11px", color: "var(--text-tertiary)" }}>{post.read_time} min read</span>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: "5px" }}>
                    <Eye size={11} color="var(--text-tertiary)" />
                    <span style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "11px", color: "var(--text-tertiary)" }}>{post.view_count.toLocaleString()} views</span>
                  </div>
                </div>

                {/* Share */}
                <div style={{ display: "flex", gap: "6px" }}>
                  {[
                    { icon: Share2, label: "Twitter", action: () => window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(post.title)}&url=${encodeURIComponent(window.location.href)}`) },
                    { icon: Link2, label: "LinkedIn", action: () => window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.href)}`) },
                    { icon: copied ? CheckCircle2 : Link2, label: copied ? "Copied!" : "Copy link", action: copyLink },
                  ].map(({ icon: Icon, label, action }) => (
                    <button
                      key={label}
                      onClick={action}
                      title={label}
                      style={{ width: "30px", height: "30px", display: "flex", alignItems: "center", justifyContent: "center", background: "var(--card)", border: "1px solid var(--border)", borderRadius: "6px", cursor: "pointer", color: "var(--text-tertiary)", transition: "all 0.18s" }}
                      onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = brandColor; (e.currentTarget as HTMLElement).style.color = brandColor; }}
                      onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = "var(--border)"; (e.currentTarget as HTMLElement).style.color = "var(--text-tertiary)"; }}
                    >
                      <Icon size={12} />
                    </button>
                  ))}
                </div>
              </div>
            </motion.div>

            {/* Article body */}
            <motion.div variants={pv(0.15)} initial="hidden" animate="visible">
              <div style={{ maxWidth: "680px" }}>
                {renderContent(post.content, brandColor)}
              </div>
            </motion.div>

            {/* Author bio */}
            <motion.div variants={pv(0.25)} initial="hidden" animate="visible">
              <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "12px", padding: "24px", marginTop: "48px", display: "flex", gap: "16px", alignItems: "flex-start" }}>
                <div style={{ width: "48px", height: "48px", borderRadius: "50%", background: `linear-gradient(135deg, ${brandColor}, color-mix(in srgb, ${brandColor} 55%, #000))`, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-syne), sans-serif", fontSize: "14px", fontWeight: 700, color: "#fff", flexShrink: 0 }}>
                  {post.author_avatar}
                </div>
                <div>
                  <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
                    <span style={{ fontFamily: "var(--font-syne), sans-serif", fontSize: "14px", fontWeight: 700, color: "var(--text-primary)" }}>{post.author_name}</span>
                    <span style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "9px", color: brandColor, background: `rgba(var(--brand-rgb),0.10)`, border: `1px solid rgba(var(--brand-rgb),0.20)`, padding: "2px 7px", borderRadius: "100px", letterSpacing: "0.08em", textTransform: "uppercase" }}>Author</span>
                  </div>
                  <p style={{ fontFamily: "var(--font-inter), sans-serif", fontSize: "13px", color: "var(--text-secondary)", lineHeight: 1.7, margin: 0 }}>
                    {post.author_bio}
                  </p>
                </div>
              </div>
            </motion.div>

            {/* Related posts */}
            <motion.div variants={pv(0.3)} initial="hidden" animate="visible" style={{ marginTop: "48px" }}>
              <div style={{ fontFamily: "var(--font-syne), sans-serif", fontSize: "11px", fontWeight: 700, color: "var(--text-tertiary)", letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: "16px" }}>
                Related Articles
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                {RELATED_POSTS.map(rp => (
                  <Link
                    key={rp.slug}
                    href={`/blog/${rp.slug}`}
                    suppressHydrationWarning
                    style={{ textDecoration: "none", display: "flex", alignItems: "center", gap: "14px", padding: "14px 16px", background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "10px", transition: "border-color 0.2s" }}
                    onMouseEnter={e => (e.currentTarget as HTMLElement).style.borderColor = `rgba(var(--brand-rgb),0.30)`}
                    onMouseLeave={e => (e.currentTarget as HTMLElement).style.borderColor = "var(--border)"}
                  >
                    <div style={{ flex: 1 }}>
                      <div style={{ fontFamily: "var(--font-syne), sans-serif", fontSize: "13px", fontWeight: 700, color: "var(--text-primary)", lineHeight: 1.35, marginBottom: "4px" }}>{rp.title}</div>
                      <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                        <span style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "9px", color: "var(--text-tertiary)", letterSpacing: "0.06em", textTransform: "uppercase" }}>{rp.category.replace("_", " ")}</span>
                        <span style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "9px", color: "var(--text-tertiary)" }}>{rp.read_time} min read</span>
                      </div>
                    </div>
                    <ChevronRight size={14} color="var(--text-tertiary)" />
                  </Link>
                ))}
              </div>
            </motion.div>

            {/* Focus keyword badge (SEO test signal) */}
            <div style={{ marginTop: "40px", padding: "14px 16px", background: `rgba(var(--brand-rgb),0.05)`, border: `1px solid rgba(var(--brand-rgb),0.15)`, borderRadius: "8px", display: "flex", alignItems: "center", gap: "8px" }}>
              <Zap size={12} color={brandColor} />
              <span style={{ fontFamily: "var(--font-dm-mono), monospace", fontSize: "10px", color: brandColor, letterSpacing: "0.08em" }}>
                AI Marketing Labs TRACKING · Focus keyword: <strong>{post.focus_keyword}</strong>
              </span>
            </div>
          </article>

          {/* Sidebar: Table of contents */}
          <aside>
            <motion.div variants={pv(0.2)} initial="hidden" animate="visible">
              <TableOfContents sections={sections} brandColor={brandColor} />

              {/* Mini newsletter */}
              <div style={{ marginTop: "32px", padding: "18px", background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "10px" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "6px", marginBottom: "8px" }}>
                  <Rss size={11} color={brandColor} />
                  <span style={{ fontFamily: "var(--font-syne), sans-serif", fontSize: "11px", fontWeight: 700, color: "var(--text-primary)" }}>Weekly Brief</span>
                </div>
                <p style={{ fontFamily: "var(--font-inter), sans-serif", fontSize: "12px", color: "var(--text-secondary)", lineHeight: 1.6, marginBottom: "12px" }}>
                  Get SEO & GEO intelligence every Tuesday.
                </p>
                <input
                  type="email"
                  placeholder="your@email.com"
                  style={{ width: "100%", padding: "8px 10px", fontFamily: "var(--font-inter), sans-serif", fontSize: "12px", color: "var(--text-primary)", background: "var(--card)", border: "1px solid var(--border)", borderRadius: "6px", outline: "none", marginBottom: "8px", boxSizing: "border-box", transition: "border-color 0.18s" }}
                  onFocus={e => (e.currentTarget.style.borderColor = brandColor)}
                  onBlur={e => (e.currentTarget.style.borderColor = "var(--border)")}
                />
                <button style={{ width: "100%", padding: "8px", fontFamily: "var(--font-inter), sans-serif", fontSize: "12px", fontWeight: 600, color: "#fff", background: `linear-gradient(135deg, ${brandColor}, color-mix(in srgb, ${brandColor} 60%, #000))`, border: "none", borderRadius: "6px", cursor: "pointer", boxShadow: "0 0 12px var(--brand-glow)" }}>
                  Subscribe
                </button>
              </div>
            </motion.div>
          </aside>
        </div>
      </div>
    </div>
  );
}
